# Generated by Django 3.2.9 on 2021-11-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
                ('image_url', models.URLField(max_length=1000)),
                ('emotion_score', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
